name: Client pipe

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Lint
        working-directory: ./client
        run: npm run eslint:check
      
      - name: Type check
        working-directory: ./client
        run: npm run type-check
